# Generated by Django 4.0.1 on 2022-08-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendart',
            name='publish',
        ),
    ]
